---
abstract: 'A tiny Qemu test image that only boots and pings'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: PITA::Test::Image::Qemu
name: PITA-Test-Image-Qemu
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  File::ShareDir: 1.00
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.41
